[build]
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/entitybtw"
  status = 200

[[redirects]]
  from = "/:splat"
  to = "https://redirect.entitybtw.ru/:splat"
  status = 301
  force = true
